### ISSUE TITLE
game crashes when reading DATETIME NULL values

### ISSUE THREAD

**Issue by Fusselwurm** [intercept/intercept-database#10]

**Comment by Fusselwurm** [comment]
my guess: null pointer exception  at https://github.com/intercept/intercept-database/blob/1194bf53267a28e46082b528570ad26cb2addfac/src/res.cpp#L45 (trying to call ´str()´on a null value)

**Comment by dedmen** [comment]
What should resultArray contain? nil/"NULL" ?
I guess "NULL" is most user friendly

**Comment by Fusselwurm** [comment]
I see that `any` is really ugly as it can result in code being ignored instead of erroring out.
But "NULL" as a string is equally wrong - going from a distinct non-value and making a string of it is... ugh...

How about `objNull`? It's not a scalar, but it's a distinct value that doesnt have the drawbacks of `nil`

**Comment by dedmen** [comment]
Actually the database returns me a string for datetime. So it gives me "NULL" so forwarding that out seems to make most sense.

**Comment by Fusselwurm** [comment]
o.O huh. ok then.

**Comment by Fusselwurm** [comment]
in a perfect world, we'd have a `date` datatype in sqf,  but we dont, sooo ok

**Comment by dedmen** [comment]
I could build one. But it seems a little out of scope.

**Comment by dedmen** [comment]
._. `dbResultToArray` docs say `(null values from the database will be returned as nil entries in the array)`

**Comment by dedmen** [comment]
We need to handle null values anyway.
Idea was to create a new dbNull type along with things like objNull and such.

isNull will return true ofc. Also want `_value isEqualTo ""` to return true if trivially doable because some people want to use empty string for null values.
Though isEqualTo variant is hard to do, and might be confusing to people who actually want to check for empty string.

**Comment by dedmen** [comment]
new dbNull type was implemented in 1.5
`dbNull == ""` returns false by default, but can be enabled in config file if needed
I heard extDB returned "" for null values so that should make transition easier.

But isEqualTo to compare with empty string is not supported, Arma engine limitations.
