### ISSUE TITLE
support reading values from TEXT column

### ISSUE THREAD

**Issue by Fusselwurm** [intercept/intercept-database#11]
currently, interceptDB does not support reading from TEXT columns (TINYTEXT, TEXT, MEDIUMTEXT, LONGTEXT, JSON) - SELECTs will omit creating a respective element in the result array

**Comment by dedmen** [comment]
I handle type `string` though.. so.. wtf..
Is text of type "BLOB" or "DATA" ? XD That's stupid.

**Comment by dedmen** [comment]
https://dev.mysql.com/doc/refman/5.5/en/c-api-prepared-statement-type-codes.html
:thinking:  text is type string. And I do handle string. So don't understand the problem here.
