### ISSUE TITLE
Connection can't be established

### ISSUE THREAD

**Issue by nflug** [intercept/intercept-database#15]
Hey,

this is my code:
```
params [
	["_configName", "", [""]],
	"_values"
];

SERVER_DB_Result        = [];
SERVER_DB_Result_parsed = [];

private _connection = dbCreateConnection "maindb";

_connection dbAddErrorHandler {
	params [
		["_errorString", "", [""]],
		["_errorCode", 0, [0]],
		["_query", "", [""]]
	];
	
	diag_log format["Error: %1", _errorString];
	diag_log format["Code: %1",  _errorCode];
	diag_log format["Query: %1", _query];
};

private _query  = dbPrepareQueryConfig [_configName, _values];
private _result = _connection dbExecuteAsync _query; 

_result dbBindCallback [{
    params ["_result", "_args"];

    SERVER_DB_Result        = dbResultToArray _result;
    SERVER_DB_Result_parsed = dbResultToParsedArray _result;
}, -1];

diag_log format["Result: %1",        SERVER_DB_Result];
diag_log format["Result parses: %1", SERVER_DB_Result_parsed];
```

The same credinals defined in the maindb account, are working on extDB.
But I can't establish a connection with Intercept DB. My results are empty or returning "TODO".
I don't get any errors in the logs and Intercept DB loads fine in the RPT.

**Comment by DragonGER** [comment]
Did you allready tried to get your data synchronously via dbExecute?
You can also try to test your connection with dbPing and look for the boolean return value. If this is not working i would recomment double checking with your yaml file.

Oh btw. if you are trying this out on your local client you need to disable battleye, but i think you got this one right?

**Comment by dedmen** [comment]
>Also i would recommand you move your diag_log stuff inside the callback because your result might be not yet pushed to your defined variables

It will definitely not be.

>My results are empty or returning "TODO".
what returns "TODO"? The return from dbExecuteAsync?
dbExecuteAsync returns a Async result that turned into string currently returns
https://github.com/intercept/intercept-database/blob/54711b61a721ddd0d0c0dba64d58a3e69508f5f7/src/res.h#L89

I should change that to "pending async result" or "completed async result" I guess. But in general turning a async result into string makes not much sense.
A bool operator would be nice so that you can wait on it 🤔

**Comment by nflug** [comment]
@DragonGER I will test it with the log function inside the callback. And it‘s running on my dedicated server, so there should be no problem with battleye. I checked my yalm few times, it‘s correct. 
@dedmen yes dbExecuteAsync returns TODO that‘s right. Maybe I add a global variable for a bool inside the callback or I 
check with some count if the array is still empty or nil. Because the code I wrote should be a new version of altis asyncCall file and it must return something to work with.

**Comment by DragonGER** [comment]
i would do a unique global var passed to the callback. Just remember to destroy the variable after used it if you don't plan on reusing it.

**Comment by dedmen** [comment]
If you want to wait till it's done. Why are you using the async variant then? Just use the non async one. it will just suspend in scheduled script.

**Comment by nflug** [comment]
> 
> 
> If you want to wait till it's done. Why are you using the async variant then? Just use the non async one. it will just suspend in scheduled script.

@dedmen I don't want till it's done. I just want to return the select with the async variant. But I don't know how to work around if I must wait for the push in the callback.

**Comment by dedmen** [comment]
You want to return the "select"? you mean ther esult for the query? meaning you want to wait till it's done.

**Comment by nflug** [comment]
@dedmen Yes I want to return the result/select. Yes I want to wait till it's done, if there is no other way. So how is this possible? I mean I can do the same with the async variant in extDB

**Comment by dedmen** [comment]
Just use the non-async variant
I assume your script is scheduled, the non-async variant will just sleep and return the result as soon as its done.

If you need to have the result ready to return it at the end of the function, it's not async.
So don't try to use the async methods for something that's not async at all.

**Comment by nflug** [comment]
You’re right, sorry. Didn‘t look into the async file from life yet. Thought it was async, even with return. My script in non-scheduled, so I need to spawn it with the non-async variant? If I want to update something without return I can use the async-variant, right?

**Comment by DragonGER** [comment]
Yes i use async for all my update and inserts
