### ISSUE TITLE
[Question] Number handling

### ISSUE THREAD

**Issue by nflug** [intercept/intercept-database#17]
Hey,

I hope I don't disturb anyone with my issues/questions.

In my database im storing the Arma3/Steam ID like this 76561198114764155.
I'm selecting the result with dbResultToParsedArray. The column type of the id is a varchar. 
If I select now the id it is shown as 7.65612e+016 because the parsed command turns the string "76561198114764155" into a number (7.65612e+016) and Arma can't handle that many digits. 

I don't want to select something without the parsed command. So I need a workaround.
Maybe you can add something in the intercept-database library that checks if a number has more digits than X and then put it into a string.

Best regards
nflug

**Comment by dedmen** [comment]
dbResultToParsedArray is https://community.bistudio.com/wiki/parseSimpleArray
which returns floats.
You can just adjust your query to turn it into a string.

`SELECT QUOTE(steamID)`
instead of
`SELECT steamID`

**Comment by nflug** [comment]
Thank you. I think I will add something in the library for me because if I want to select something without the parsed command I have double quote and I don‘t want to check everytime for them.
