### ISSUE TITLE
dbIsConnected does not work immediately after dbCreateConnection

### ISSUE THREAD

**Issue by Xeno69** [intercept/intercept-database#5]
When I create a connection with dbCreateConnection and call dbIsConnected immediately afterwards it returns nothing.

Furthermore, calling a dbPing also immediately after dbCreateConnection crashes the game.

I run something like the following code in preinit (CfgFunctions):

> _interceptdb = true;		
> DB_CON = dbCreateConnection "mydb";
> if (dbIsConnected DB_CON) then {
> 	diag_log ["InterceptDB connected!!!"];
> 	if (dbPing DB_CON) exitWith {
> 		diag_log ["InterceptDB mydb DB found!!!"];
> 	};
> 	_interceptdb = false;
> } else {
> 	_interceptdb = false;
> 	diag_log ["InterceptDB NOT connected!!!"];
> };

If I try a dbIsConnected later it works fine.

Btw, parse array works fine.

**Comment by dedmen** [comment]
That is expected behavior.
Connection is only established at the first query being executed.

>Furthermore, calling a dbPing also immediately after dbCreateConnection crashes the game.
Yeah I seem to have failed something in there. dbPing in general seems to be broken.

>and call dbIsConnected immediately afterwards it returns nothing.
Nothing? aka nil? or nothing aka false?

**Comment by Xeno69** [comment]
I'm not at home so yeah, could be false for dbIsConnected (tested last night and wrote all that from my head).

So would a dbPing (if it is working) also create a DB connection?

**Comment by dedmen** [comment]
>So would a dbPing (if it is working) also create a DB connection?

Yes definitely. I already have a crashdump of dbPing crashing so that should be easy to fix. Already on it right now.

**Comment by dedmen** [comment]
Quick and dirty on the go build with a fix for dbPing. Not sure if I can push the real release today or tomorrow.
[intercept-database_x64.zip](https://github.com/intercept/intercept-database/files/3033927/intercept-database_x64.zip)

**Comment by Xeno69** [comment]
Hm, this is what I get now (with the latest intercept-database_x64.dll from the file above):

> "Intercept-DB ping exception type error"

when running a dbPing connection.

**Comment by dedmen** [comment]
Ugh... I hate this :D
Apparently `SELECT 1` doesn't return a unsigned number then -.-

**Comment by Xeno69** [comment]
Other than that it seems to work quite fine now.

Will do some real MP mission tests over the next days, I have both now running, extDB3 and interceptDB.

One thing, please add in the Wiki that dbCreateConnection is case sensitive (maybe other commands too)
Others might save some time by knowing that :)

**Comment by dedmen** [comment]
>One thing, please add in the Wiki that dbCreateConnection is case sensitive

Didn't even know it was :D Never thought about it.

The prepareQueryConfig commands are also case sensitive.

I added all that to the wiki, together with the note that connection is only established at first query.

**Comment by dedmen** [comment]
https://cdn.discordapp.com/attachments/462378164971372564/564877866865524766/intercept-database_x64.dll
build with dbPing fixed. Sorry that I can't push a real release currently.
