### ISSUE TITLE
option to disable dynamic query creation

### ISSUE THREAD

**Issue by Legodev** [intercept/intercept-database#6]
For server security its vital to be able to disable dbPrepareQuery on productive servers and only allow the use of stored procedures using dbPrepareQueryConfig.

**Comment by dedmen** [comment]
Needs new section in config for global settings.
This setting should be global not connection specific like the worker thread count will probably be.

**Comment by dedmen** [comment]
ddb54b9cbeffd7a763ff0159b81536693da5b4ec
